### ISSUE TITLE
rails integration

### ISSUE THREAD

**Issue by TomK32** [jferris/effigy#1]
Wouldn't it make sense to assume that everything that is in your index.html.effigy is evaluated in the transform method anyways and drop a few lines of code?

**Comment by jferris** [comment]
That would prevent people from breaking out their views into other methods, which is one of the things I like about Effigy views being actual Ruby classes. Honestly, I haven't gotten to use Effigy enough to tell whether or not that's something I actually want to do, but for now I'd like to keep them as visible classes.
