### ISSUE TITLE
Option to bring back HTML with no DOCTYPE

### ISSUE THREAD

**Issue by croaky** [jferris/effigy#11]
Right now, rendering with Effigy brings back the DOCTYPE, html, and body tags. My use case is on an Ajax call which just returns an HTML fragment that jQuery then replaces in the DOM. The extra tags around it messes up.

My current hack is:

```
def output
  current_context.to_html.sub(/.*<body>/, '').sub(/<\/body>.*/, '')
end
```

**Comment by jferris** [comment]
Fixed by 978fd82e42212ead3b5691a71381135de4419229
