### ISSUE TITLE
core_ext needs to be used in lib, not just spec

### ISSUE THREAD

**Issue by croaky** [jferris/effigy#2]
Otherwise this will always error with NoMethodError:

```
f('h2 a').attr(:href, job.company_url)
```

Patch here: http://gist.github.com/276921

**Comment by croaky** [comment]
patch: http://github.com/dancroak/effigy/commit/73c64da985146025012b7d6dc15de9c75252d5b8

**Comment by jferris** [comment]
Fixed issues with requires; closed by 0aaf7d27cff4502662a8a3d43d2d8ab0cbcceeef
