### ISSUE TITLE
Default implementation of Effigy creates invalid HTML5 markup

### ISSUE THREAD

**Issue by jmreidy** [jferris/effigy#6]
Effigy views create their output using the "output" method, which defaults to using Nokgiri's "to_xhtml" method. This method appends "xmlns" info to the root <html> tag, regardless of whether the HTML document actually has an XHTML doctype. This issue can be resolved by overiding "output" and calling current_context.to_html instead. 

It might be helpful for docs to be updated to reflect this use case.

**Comment by jferris** [comment]
Output valid HTML by default instead of XHTML; closed by eedd38bce63cfbe7ea4bfb27ef640f152e635223
