### ISSUE TITLE
Separates the project in two: effigy and effigy-rails

### ISSUE THREAD

**Issue by hallison** [jferris/effigy#7]
I see which the most issues point to Rails. My idea is separates the project. The first will be the source base and the main goal is be free of the frameworks.  So, others developers can design extensions exclusively for others fameworks, for example Sinatra.

The second will be effigy-rails, of course!

Thanks.

**Comment by its-danny** [comment]
Sounds like a winner to me!

**Comment by jferris** [comment]
I like the idea of separate projects, but I think Effigy is too young and small to see much benefit. The added overhead of maintaining 3 Github projects, repos, test suites, gems, and release cycles will definitely outweight any cleanliness gained. I want to keep support for other frameworks in the Effigy gem for now.

**Comment by Papipo** [comment]
I think that adding support for tilt would be enough, no?
