### ISSUE TITLE
use Nokogiri::HTML.parse instead of ::XML.parse

### ISSUE THREAD

**Issue by croaky** [jferris/effigy#8]
XML does not like HTML fragments. There's also Nokogiri::HTML.fragment but it caused other problems with Effigy when I tried it. Simply replacing with HTML.parse passes all tests.

Patch:
http://github.com/dancroak/effigy/commit/6a5500fdd508d591fa7a92b6ba1e9382dc68366d

**Comment by jferris** [comment]
What other problems did #fragment cause? Using #parse causes the Rails layouts tests to fail for me, and insists on wrapping layouts with <html> and DOCTYPE declarations.

**Comment by croaky** [comment]
If fragment does the trick, roll with it. I was probably changing too many variables at once, didn't exactly have a "control" situation.

**Comment by jferris** [comment]
Cool - I'll assume #fragment is all good until we learn otherwise.
